name = "CrimsonSkyline"
uuid = "b920cfb2-02b9-492b-931b-17200f17e6e0"
authors = ["daviddewhurst <drd@davidrushingdewhurst.com>"]
version = "0.1.0"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
IJulia = "7073ff75-c697-5162-941a-fcdaad2a7d2a"
JuliaDB = "a93385a2-3734-596a-9a66-3cfbb77141e6"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
PrettyPrint = "8162dcfd-2161-5ef2-ae6c-7681170c5f98"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StatsBase = "2913bbd2-ae8a-5f71-8c99-4fb6c76f3a91"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Zygote = "e88e6eb3-aa80-5325-afca-941959d7151f"
